apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversiktsrv
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - "https://syfooversiktsrv.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-fss
    outbound:
      external:
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
      rules:
        - application: syfobehandlendeenhet
        - application: syfooversiktsrv-redis
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: syfooversiktsrv-db
        diskAutoresize: true
  kafka:
    pool: nav-dev
  envFrom:
    - secret: syfooversiktsrv-redis-password
  env:
    - name: KTOR_ENV
      value: production
    - name: REDIS_HOST
      value: "syfooversiktsrv-redis.teamsykefravr.svc.cluster.local"
    - name: EREG_URL
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.dev.intern.nav.no"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
    - name: TOGGLE_KAFKA_AKTIVITETSKRAV_VURDERING_PROCESSING_ENABLED
      value: "true"
    - name: TOGGLE_KAFKA_IDENTHENDELSE_UPDATES_ENABLED
      value: "true"

