apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversiktsrv
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 10
    timeout: 5
    failureThreshold: 10
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - "https://syfooversiktsrv.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      external:
        - host: "ereg-services.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: syfobehandlendeenhet
        - application: syfooversiktsrv-redis
        - application: isarbeidsuforhet
        - application: istilgangskontroll
        - application: ishuskelapp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: syfooversiktsrv-db
        diskAutoresize: true
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: syfooversiktsrv-redis-password
  env:
    - name: KTOR_ENV
      value: production
    - name: REDIS_HOST
      value: "syfooversiktsrv-redis.teamsykefravr.svc.cluster.local"
    - name: EREG_URL
      value: "https://ereg-services.prod-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet"
    - name: ARBEIDSUFORHETVURDERING_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isarbeidsuforhet"
    - name: ARBEIDSUFORHETVURDERING_URL
      value: "http://isarbeidsuforhet"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_HOST
      value: "http://istilgangskontroll"
    - name: ISHUSKELAPP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ishuskelapp"
    - name: ISHUSKELAPP_URL
      value: "http://ishuskelapp"
    # Bruk samme dato i enhetens-oversikt-query og index
    - name: ARENA_CUTOFF
      value: "2023-03-10"
    - name: CRONJOB_BEHANDLENDE_ENHET_INTERVAL_DELAY_MINUTES
      value: "15"
