apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversiktsrv
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfooversiktsrv.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/prod/srvsyfooversiktsrv"
        mountPath: "/secrets/serviceuser/syfooversiktsrv"
  webproxy: true
  env:
    - name: SYFOOVERSIKTSRV_DB_URL
      value: jdbc:postgresql://fsspgdb.adeo.no:5432/syfooversiktsrv
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: KTOR_ENV
      value: production
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.intern.nav.no"
