apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversiktsrv
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfooversiktsrv.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-fss
    outbound:
      external:
        - host: "kafka-schema-registry.nais-q.adeo.no"
        - host: "isproxy.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "syfo-tilgangskontroll.dev-fss-pub.nais.io"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: syfooversiktsrv-db
        diskAutoresize: true
  kafka:
    pool: nav-dev
  envFrom:
    - secret: syfooversiktsrv-redis-password
    - secret: syfooversiktsrv-serviceuser
  env:
    - name: KTOR_ENV
      value: production
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: "https://kafka-schema-registry.nais-q.adeo.no"
    - name: REDIS_HOST
      value: "syfooversiktsrv-redis.teamsykefravr.svc.cluster.local"
    - name: ISPROXY_CLIENT_ID
      value: "dev-fss.teamsykefravr.isproxy"
    - name: ISPROXY_URL
      value: "https://isproxy.dev-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.dev-fss-pub.nais.io"
    - name: TOGGLE_KAFKA_CONSUMER_ENABLED
      value: "true"
    - name: TOGGLE_KAFKA_OPPFOLGINGSTILFELLE_PERSON_PROCESSING_ENABLED
      value: "true"
    - name: TOGGLE_PERSON_OPPFOLGINGSTILFELLE_VIRKSOMHETSNAVN_CRONJOB_ENABLED
      value: "false"
