apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversiktsrv
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 10
    timeout: 5
    failureThreshold: 10
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - "https://syfooversiktsrv.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfobehandlendeenhet
        - application: syfooversikt
        - application: syfomodiaperson
        - application: modia-robot-api
          namespace: personoversikt
        - application: oppgave
          namespace: aap
    outbound:
      external:
        - host: "ereg-services.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
      rules:
        - application: syfobehandlendeenhet
        - application: isarbeidsuforhet
        - application: isaktivitetskrav
        - application: ismanglendemedvirkning
        - application: istilgangskontroll
        - application: ishuskelapp
        - application: ismeroppfolging
        - application: isdialogmotekandidat
        - application: syfoveileder
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  valkey:
    - instance: cache
      access: readwrite
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: syfooversiktsrv-db
        diskAutoresize: true
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: KTOR_ENV
      value: production
    - name: EREG_URL
      value: "https://ereg-services.prod-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet"
    - name: SYFOVEILEDER_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoveileder"
    - name: SYFOVEILEDER_URL
      value: "http://syfoveileder"
    - name: ARBEIDSUFORHETVURDERING_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isarbeidsuforhet"
    - name: ARBEIDSUFORHETVURDERING_URL
      value: "http://isarbeidsuforhet"
    - name: AKTIVITETSKRAV_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isaktivitetskrav"
    - name: AKTIVITETSKRAV_URL
      value: "http://isaktivitetskrav"
    - name: MANGLENDEMEDVIRKNING_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ismanglendemedvirkning"
    - name: MANGLENDEMEDVIRKNING_URL
      value: "http://ismanglendemedvirkning"
    - name: ISMEROPPFOLGING_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ismeroppfolging"
    - name: ISMEROPPFOLGING_URL
      value: "http://ismeroppfolging"
    - name: ISDIALOGMOTEKANDIDAT_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmotekandidat"
    - name: ISDIALOGMOTEKANDIDAT_URL
      value: "http://isdialogmotekandidat"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_HOST
      value: "http://istilgangskontroll"
    - name: ISHUSKELAPP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ishuskelapp"
    - name: ISHUSKELAPP_URL
      value: "http://ishuskelapp"
    - name: CRONJOB_BEHANDLENDE_ENHET_INTERVAL_DELAY_MINUTES
      value: "15"
