package no.nav.syfo.personstatus.domain

enum class OversikthendelseType {
    MOTEBEHOV_SVAR_MOTTATT,
    MOTEBEHOV_SVAR_BEHANDLET,
    MOTEPLANLEGGER_ALLE_SVAR_MOTTATT,
    MOTEPLANLEGGER_ALLE_SVAR_BEHANDLET,
    OPPFOLGINGSPLANLPS_BISTAND_MOTTATT,
    OPPFOLGINGSPLANLPS_BISTAND_BEHANDLET,
}
