package no.nav.syfo.personstatus.domain

enum class OversikthendelseType {
    MOTEBEHOV_SVAR_MOTTATT,
    MOTEBEHOV_SVAR_BEHANDLET,
    OPPFOLGINGSPLANLPS_BISTAND_MOTTATT,
    OPPFOLGINGSPLANLPS_BISTAND_BEHANDLET,
    DIALOGMOTESVAR_MOTTATT,
    DIALOGMOTESVAR_BEHANDLET,
    BEHANDLERDIALOG_SVAR_MOTTATT,
    BEHANDLERDIALOG_SVAR_BEHANDLET,
}
