-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO cloudsqliamuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cloudsqliamuser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO cloudsqliamuser;
