name: kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/kafka.yaml'
      - '.nais/kafka/**'

jobs:
  deploy-kafka-dev:
    name: Deploy Kafka topic to NAIS dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/oversikthendelse.yaml
          VARS: .nais/kafka/dev.json

  deploy-kafka-prod:
    name: Deploy Kafka topic to NAIS prod-gcp
    needs: deploy-kafka-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/oversikthendelse.yaml
          VARS: .nais/kafka/prod.json

